# Generated by Django 4.0 on 2022-10-14 19:03

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.airports')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.airports')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FakePassportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('passNum', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=main.models.rename)),
                ('options', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.airports')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.verifier')),
            ],
        ),
    ]
