# Generated by Django 4.0 on 2022-10-14 19:11

from django.db import migrations
import random
from django.conf import settings
import os
from django.core.files import File


def load_data(apps, schema_editor):
    # Top 10 sample airports
    Airports = apps.get_model("main", "Airports")
    Goa_Airport = Airports(airport="Dabolim Airport, Goa")
    Goa_Airport.save()
    Chennai_Airport = Airports(airport="Chennai International Airport, Chennai")
    Chennai_Airport.save()
    Delhi_Airport = Airports(airport="Indira Gandhi International Airport, Delhi")
    Delhi_Airport.save()
    Kolkata_Airport = Airports(airport="Kolkata International Airport, Kolkata")
    Kolkata_Airport.save()
    Banglore_Airport = Airports(airport="Kempegowda International Airport, Bangalore")
    Banglore_Airport.save()
    Hyderabad_Airport = Airports(
        airport="Rajiv Gandhi International Airport, Hyderabad"
    )
    Hyderabad_Airport.save()
    Leh_Airport = Airports(airport="Kushok Bakula Rimpochee Airport, Leh")
    Leh_Airport.save()
    Mumbai_Airport = Airports(
        airport="Chhatrapati Shivaji International Airport, Mumbai"
    )
    Mumbai_Airport.save()
    Srinagar_Airport = Airports(airport="Srinagar International Airport, Srinagar")
    Srinagar_Airport.save()
    Shimla_Airport = Airports(airport="Shimla Airport, Shimla")
    Shimla_Airport.save()

    # 10 Verifier accounts for the 10 airports
    User = apps.get_model("auth", "User")
    Verifier = apps.get_model("main", "Verifier")

    Verifier_Goa_Airport_User = User(username="Goa_V", password="passport@123")
    Verifier_Goa_Airport_User.save()
    Verifier_Goa_Airport = Verifier(
        user=Verifier_Goa_Airport_User, email="abc@abc.com", airport=Goa_Airport
    )
    Verifier_Goa_Airport.save()

    Verifier_Chennai_Airport_User = User(username="Chennai_V", password="passport@123")
    Verifier_Chennai_Airport_User.save()
    Verifier_Chennai_Airport = Verifier(
        user=Verifier_Chennai_Airport_User, email="abc@abc.com", airport=Chennai_Airport
    )
    Verifier_Chennai_Airport.save()

    Verifier_Delhi_Airport_User = User(username="Delhi_V", password="passport@123")
    Verifier_Delhi_Airport_User.save()
    Verifier_Delhi_Airport = Verifier(
        user=Verifier_Delhi_Airport_User, email="abc@abc.com", airport=Delhi_Airport
    )
    Verifier_Delhi_Airport.save()

    Verifier_Kolkata_Airport_User = User(username="Kolkata_V", password="passport@123")
    Verifier_Kolkata_Airport_User.save()
    Verifier_Kolkata_Airport = Verifier(
        user=Verifier_Kolkata_Airport_User, email="abc@abc.com", airport=Kolkata_Airport
    )
    Verifier_Kolkata_Airport.save()

    Verifier_Banglore_Airport_User = User(
        username="Banglore_V", password="passport@123"
    )
    Verifier_Banglore_Airport_User.save()
    Verifier_Banglore_Airport = Verifier(
        user=Verifier_Banglore_Airport_User,
        email="abc@abc.com",
        airport=Banglore_Airport,
    )
    Verifier_Banglore_Airport.save()

    Verifier_Hyderabad_Airport_User = User(
        username="Hyderabad_V", password="passport@123"
    )
    Verifier_Hyderabad_Airport_User.save()
    Verifier_Hyderabad_Airport = Verifier(
        user=Verifier_Hyderabad_Airport_User,
        email="abc@abc.com",
        airport=Hyderabad_Airport,
    )
    Verifier_Hyderabad_Airport.save()

    Verifier_Leh_Airport_User = User(username="Leh_V", password="passport@123")
    Verifier_Leh_Airport_User.save()
    Verifier_Leh_Airport = Verifier(
        user=Verifier_Leh_Airport_User, email="abc@abc.com", airport=Leh_Airport
    )
    Verifier_Leh_Airport.save()

    Verifier_Mumbai_Airport_User = User(username="Mumbai_V", password="passport@123")
    Verifier_Mumbai_Airport_User.save()
    Verifier_Mumbai_Airport = Verifier(
        user=Verifier_Mumbai_Airport_User, email="abc@abc.com", airport=Mumbai_Airport
    )
    Verifier_Mumbai_Airport.save()

    Verifier_Srinagar_Airport_User = User(
        username="Srinagar_V", password="passport@123"
    )
    Verifier_Srinagar_Airport_User.save()
    Verifier_Srinagar_Airport = Verifier(
        user=Verifier_Srinagar_Airport_User,
        email="abc@abc.com",
        airport=Srinagar_Airport,
    )
    Verifier_Srinagar_Airport.save()

    Verifier_Shimla_Airport_User = User(username="Shimla_V", password="passport@123")
    Verifier_Shimla_Airport_User.save()
    Verifier_Shimla_Airport = Verifier(
        user=Verifier_Shimla_Airport_User, email="abc@abc.com", airport=Shimla_Airport
    )
    Verifier_Shimla_Airport.save()

    verifier_accounts = [
        Verifier_Goa_Airport,
        Verifier_Chennai_Airport,
        Verifier_Delhi_Airport,
        Verifier_Kolkata_Airport,
        Verifier_Banglore_Airport,
        Verifier_Hyderabad_Airport,
        Verifier_Leh_Airport,
        Verifier_Mumbai_Airport,
        Verifier_Srinagar_Airport,
        Verifier_Shimla_Airport,
    ]

    # 10 Security accounts for the 10 airports
    User = apps.get_model("auth", "User")
    Security = apps.get_model("main", "Security")

    Security_Goa_Airport_User = User(username="Goa_S", password="passport@123")
    Security_Goa_Airport_User.save()
    Security_Goa_Airport = Security(
        user=Security_Goa_Airport_User, email="abc@abc.com", airport=Goa_Airport
    )
    Security_Goa_Airport.save()

    Security_Chennai_Airport_User = User(username="Chennai_S", password="passport@123")
    Security_Chennai_Airport_User.save()
    Security_Chennai_Airport = Security(
        user=Security_Chennai_Airport_User, email="abc@abc.com", airport=Chennai_Airport
    )
    Security_Chennai_Airport.save()

    Security_Delhi_Airport_User = User(username="Delhi_S", password="passport@123")
    Security_Delhi_Airport_User.save()
    Security_Delhi_Airport = Security(
        user=Security_Delhi_Airport_User, email="abc@abc.com", airport=Delhi_Airport
    )
    Security_Delhi_Airport.save()

    Security_Kolkata_Airport_User = User(username="Kolkata_S", password="passport@123")
    Security_Kolkata_Airport_User.save()
    Security_Kolkata_Airport = Security(
        user=Security_Kolkata_Airport_User, email="abc@abc.com", airport=Kolkata_Airport
    )
    Security_Kolkata_Airport.save()

    Security_Banglore_Airport_User = User(
        username="Banglore_S", password="passport@123"
    )
    Security_Banglore_Airport_User.save()
    Security_Banglore_Airport = Security(
        user=Security_Banglore_Airport_User,
        email="abc@abc.com",
        airport=Banglore_Airport,
    )
    Security_Banglore_Airport.save()

    Security_Hyderabad_Airport_User = User(
        username="Hyderabad_S", password="passport@123"
    )
    Security_Hyderabad_Airport_User.save()
    Security_Hyderabad_Airport = Security(
        user=Security_Hyderabad_Airport_User,
        email="abc@abc.com",
        airport=Hyderabad_Airport,
    )
    Security_Hyderabad_Airport.save()

    Security_Leh_Airport_User = User(username="Leh_S", password="passport@123")
    Security_Leh_Airport_User.save()
    Security_Leh_Airport = Security(
        user=Security_Leh_Airport_User, email="abc@abc.com", airport=Leh_Airport
    )
    Security_Leh_Airport.save()

    Security_Mumbai_Airport_User = User(username="Mumbai_S", password="passport@123")
    Security_Mumbai_Airport_User.save()
    Security_Mumbai_Airport = Security(
        user=Security_Mumbai_Airport_User, email="abc@abc.com", airport=Mumbai_Airport
    )
    Security_Mumbai_Airport.save()

    Security_Srinagar_Airport_User = User(
        username="Srinagar_S", password="passport@123"
    )
    Security_Srinagar_Airport_User.save()
    Security_Srinagar_Airport = Security(
        user=Security_Srinagar_Airport_User,
        email="abc@abc.com",
        airport=Srinagar_Airport,
    )
    Security_Srinagar_Airport.save()

    Security_Shimla_Airport_User = User(username="Shimla_S", password="passport@123")
    Security_Shimla_Airport_User.save()
    Security_Shimla_Airport = Security(
        user=Security_Shimla_Airport_User, email="abc@abc.com", airport=Shimla_Airport
    )
    Security_Shimla_Airport.save()

    passport_list = """77RUAMK
PTRCD1V
F1J6RQN
RP8807U
EXYL53W
6B8OZ82
BTY7392
77D3Z1Q
U4ZD4ZI
3RO4MV0
KVZBLQ5
3610XBH
DJREWCK
6R1WJIE
4NOB56H
6XYW2V8
600Y5VM
ISB9HLC
91XXE44
GCRXFU0
8YXNXC4
GE76XPC
MZEVKQO
GHGGT0E
E3KGREG
C2QZQ0S
O937UZP
CEWC0FQ
DAYCOVM
61R3BSP
1LVDT37
""".split(
        "\n"
    )

    time_list = """1566263493
1627414232
1600559016
1609325010
1600975597
1493116521
1624878170
1563063705
1517781871
1635951317
1505575768
1607149314
1559557610
1584134206
1597975045
1542798463
1516258149
1534883464
1636278489
1495861920
1508721956
1629533102
1499734122
1550581203
1518054264
1629685364
1568305589
1587532519
1497022701
1570166651
1593434568
1572144117
1523690075
1545801458
1613161852
1504490290
1647848323
1535155570
1526890992
1623884547
1551300829
1630463121
1587869679
1620505655
1607503170
1596952725
1509102821
1588374145
1616628886
1537498013
1539534699
1498374480
1540452149
1608332172
1612106726
1566116237
1581251468
1543176632
1510933172
1585658082
1649230692
1532667079
1544424577
1642431591
1597384912
1522858644
1605124401
1627670532
1538151749
1635934763
1515165238
1621784936
1551991734
1605774351
1574131083
1613162585
1508391590
1633967452
1597008661
1607605770
1611348091
1624451297
1534569643
1537464851
1647330009
1608193478
1514173403
1555602170
1594813850
1511941321
1644841997
1552193985
1648166589
1529029786
1522417126
1641992251
1623389942
1621955180
1584974659
1538258780
""".split(
        "\n"
    )

    options_list = [
        "Face Image",
        "Signature",
        "Type",
        "Country Code",
        "Passport No",
        "Surname",
        "Given Name",
        "Nationality",
        "Date of Birth",
        "Place of Birth",
        "Place of issue",
        "Date of issue",
        "Date of expiry",
        "Name of Father/Legal Guardian",
        "Name of Mother",
        "Name of Spouse",
        "Old Passport Number",
        "Old Passport Place of Issue",
        "Old Passport Date of Issue",
        "File number",
        "Address Line 1",
        "Address Line 2",
        "Address Line 3",
    ]

    # Creating 100 fake passport reports
    FakePassportReport = apps.get_model("main", "FakePassportReport")
    for i in range(100):
        verifier = verifier_accounts[random.randint(0, len(verifier_accounts) - 1)]
        airport = verifier.airport
        time = time_list[i]
        passNum = passport_list[random.randint(0, len(passport_list) - 1)]
        options = ";".join(random.sample(options_list, k=3))
        remarks = "None"
        Object = FakePassportReport(
            verifier=verifier,
            airport=airport,
            time=time,
            passNum=passNum,
            image=File(
                file=open(
                    os.path.join(settings.BASE_DIR, "main/SampleImage.png"), "rb"
                ),
                name=verifier.user.username + "_" + time + ".png",
            ),
            options=options,
            remarks=remarks,
        )
        Object.save()


def delete_data(apps, schema_editor):
    FakePassportReport = apps.get_model("main", "FakePassportReport")
    FakePassportReport.objects.all().delete()

    Security = apps.get_model("main", "Security")
    Security.objects.all().delete()

    Verifier = apps.get_model("main", "Verifier")
    Verifier.objects.all().delete()

    Airports = apps.get_model("main", "Airports")
    Airports.objects.all().delete()

    User = apps.get_model("auth", "User")
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
